language: node_js
node_js:
  - stable

branches:
  only:
    - develop
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test
after_success: 
  - npm run coveralls
sudo: false
