language: node_js
node_js:
  - stable
branches:
  only:
    - develop
services:
  - postgresql
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install coveralls
script:
  - npm run test
after_success: 
  - npm run coveralls
sudo: false
